### PR TITLE
Make sure to use existing version of binary package

### PR DESCRIPTION
**Pull request by kuznero**
Following up on incident #506

### CODE REVIEW

**Comment by kuznero** [comment]
Thanks, @puffnfresh 
As a side question: is there any way to install eta/etlas into global space? I was trying to:

```
$ nix-build -A eta-build-shell
```

Hoping then to `nix-env -i ./result`, but `nix-build` fails. What is the best of to do this?

**Comment by rahulmutt** [comment]
@puffnfresh I'll merge this and then you'll send another PR for the graceful handling of previous versions?

**Comment by puffnfresh** [comment]
@kuznero I think this :crossed_fingers:

```
nix-env -f . -iA haskell.packages.ghc7103.eta haskell.packages.ghc7103.etlas
```

@rahulmutt yes please!

**Comment by kuznero** [comment]
@puffnfresh excellent! thanks a ton!

**Comment by kuznero** [comment]
@rahulmutt Thanks for taking the changes in!
@puffnfresh Thanks for the tip! Exactly what I need now.

**Comment by kuznero** [comment]
Are there any plans on pushing eta/etlas packages to nixpkgs?

**Comment by puffnfresh** [comment]
@kuznero I've been kinda waiting for Eta to be available via Hackage. @rahulmutt do you think that'll happen sometime?

**Comment by rahulmutt** [comment]
Yes, within the next couple of months. I want to be able to compile ghc-mod using eta as a dependency and that'll require lots of changes in terms of API exports. Once that part is stable, I'm planning on doing a Hackage release.

**Pull request merged**
