### PR TITLE
Windows support iconv

### PR DESCRIPTION
**Pull request by jneira**
Changes to windows.support (#106):
- Translating debug.sh to debug.cmd
- Implement errno handling in java
- Translating iconv c calls in java ones

### CODE REVIEW

**Comment by jneira** [comment]
one comment about performance: the java decode step uses an intermediate output buffer as bigger as the input one so the program will use more memory than the ghc version

**Comment by rahulmutt** [comment]
Great work @jneira! Please rebase one more time because I've updated the testing scripts for Appveyor and Travis.

**Comment by jneira** [comment]
@rahulmutt  i've done the rebase (with some strange problems) and it seems to be correct

**Comment by rahulmutt** [comment]
Thanks! It looks like the AppVeyor build printed "Hello World!". I'll just wait for it to compile the rest of the packages and see if it encounters the patches problem like you did.

**Comment by rahulmutt** [comment]
The AppVeyor build failed, but that seems to be an orthogonal problem. I'll merge.

**Pull request merged**
