### PR TITLE
fix #454

### LINKED ISSUE #454: eta: panic! (the 'impossible' happened)         InvalidAbsFile "..
when there is a  -i option that has references the parent directory ".." : 

```
tests# eta  -i../src Test.hs
[1 of 7] Compiling Transient.Internals ( ../src/Transient/Internals.hs, ../src/Transient/Internals.jar ) [flags changed]
eta: panic! (the 'impossible' happened)
  (Eta version 0.0.9b2):
        InvalidAbsFile "../src/Transient/Internals.jar"
```

### PR DESCRIPTION
**Pull request by agocorona**
Checked with my use cases.

### CODE REVIEW

**Comment by rahulmutt** [comment]
Looks good. Let's see how the build goes.

Also, we may hit [this](http://neilmitchell.blogspot.co.uk/2015/10/filepaths-are-subtle-symlinks-are-hard.html) problem in the future, but I think it won't be too much of a problem for the use case of source code for projects.

**Comment by agocorona** [comment]
For that reason probably  `canonicalizePath` actually acess to the path, to determine the real parent directory (I guess)

**Comment by rahulmutt** [comment]
Hmm yes, but canonicalizePath doesn't work for non-existent paths. Hmm I wonder if there's a way to normalise non-existent paths by stripping of the right side of a path until you get an existant path and then slap on the part your stripped off.

What do you think? Should we be worried about that obscure case?

**Comment by agocorona** [comment]
mmm  now I remember that canonicalizePath is not capable of elimianting ".."  even if the file exist. At least in my case.  I think that this only hit in rare cases and even in these cases the programmer has the option to write the path without .. if it points to a symbolic link

**Comment by rahulmutt** [comment]
Ok cool. I'll merge then.

**Pull request merged**
