### PR TITLE
Export Java.Do module

### PR DESCRIPTION
**Pull request by csierra**
Create a Java.Do module. 
This module defines new type classes and helper functions to work with JWT types _shaped_ like functors, applicative or monads. 
This PR relates to https://github.com/typelead/eta/issues/243

### CODE REVIEW

**Comment by csierra** [comment]
hey @rahulmutt, 
I try to condense here the discussion we maintained through gists and the work you sent me to deal with  `Function`s of any arity. 
I took me long but I was able to make it work with both my validation and OSGi _"functional java libraries"_ so this should be, at least, a good start for the module. 
Please accept my apologies if the formatting of the code or the PR is not the appropiate. Feel free to shape it as you need. 
Please let me know if you have any suggestions.

Thanks in advance.

**Comment by rahulmutt** [comment]
Looks good, thanks! If the examples you've worked out are available publicly, please do share on Gitter.

**Comment by csierra** [comment]
they are still not available but I can try and groom and upload them

**Comment by rahulmutt** [comment]
No problem. Take your time.

**Pull request merged**
