### PR TITLE
Print error message and exit on similar names.

### PR DESCRIPTION
**Pull request by pparkkin**
Find identifiers with names differing only in case. If found, print error message and exit.

See issue https://github.com/typelead/eta/issues/31.

### CODE REVIEW

**Comment by rahulmutt** [comment]
Great start @pparkkin! Some feedback:

High Priority:
- In the very beginning of `rnSrcDecls`, there's a call to `getLocalNonValBinders` (located in `ETA.Rename.RnNames`) where it checks for duplicate names. It makes sense to integrate your pass in that function somewhere so that it can fail earlier and do less work.
- Try to use the existing error throwing mechanism in the `TcM` monad. Checkout the functions `addErr`, `failWith`, `addErrAt`, `addErrs` in `ETA.TypeCheck.TcRnMonad`.

Optional:
- The runtime complexity of the function that detects similar names is `O(n^2)`, can you make it a fold with a `Map` that stores the lower case names as it runs the pass to bring it down to say `O(nlog(n))`? This is not too much of a priority, but if it sounds interesting to work on you can give it a try.

**Comment by pparkkin** [comment]
Thanks for the review!

I don't think `getLocalNonValBinders` handles the function names at all. To me it looks like they're part of `val_decls`, which is handled in `rnTopBindsLHS` (really `rnValBindsLHS`). That's where I moved the checking to.

I also use `failWith` now. Right now the error message shows line/column as `1:1`. I'll try to find out whether I can get the correct line number.

I'll also do the optimization you mention when I get some more time.

**Comment by pparkkin** [comment]
Implemented the requested optimization, and changed it to output line numbers.

Looks something like this now.
```
Main.hs:8:1:
    Multiple declarations with names differing only in case.
    Declared at: Main.hs:5:1
                 Main.hs:8:1
```

**Comment by rahulmutt** [comment]
Awesome work @pparkkin! The build failed because of the following error:
```haskell
lib/Data/Time/Format/Parse.hs:179:1:
    Multiple declarations with names differing only in case.
    Declared at: lib/Data/Time/Format/Parse.hs:135:1
                         lib/Data/Time/Format/Parse.hs:179:1
```
Indeed, `Data.Time.Format.Parse` uses `readSTime` and `readsTime` in the same file! In practice, this would've caused a runtime bug when parsing time formats. Thanks to your changes, we can now detect them beforehand!

So what I'll do is update the time patches and rerun the build until it works. From your side, everything seems to be fine.

**Comment by rahulmutt** [comment]
I just noticed that the following warnings:
```
/home/travis/build/typelead/eta/compiler/ETA/Rename/RnBinds.hs:50:1: Warning:
    The import of ‘sortBy, intercalate, groupBy’
    from module ‘Data.List’ is redundant
/home/travis/build/typelead/eta/compiler/ETA/Rename/RnBinds.hs:305:22: Warning:
    Defined but not used: ‘name’
```
Can you fix those please?

**Comment by pparkkin** [comment]
Done.

I was looking for a way to get the warnings to show. I see them now. Seems like I just missed them in the `stack` output before.

**Comment by rahulmutt** [comment]
Great. By the way, do your changes work on data constructors and type constructors as well?

**Comment by pparkkin** [comment]
Looks like no. I'll try to get that fixed as soon as I can.

Also, I found out it doesn't only check toplevel definitions, but it will also error out on something like this.

```haskell
module Main where

main :: IO ()
main = do
  let
    hW = "helloWorld"
    hw = "helloworld"
  print hW
  print hw
```

I'll get that sorted out too.

**Comment by rahulmutt** [comment]
No problem. Since you've done the core algorithm, I don't think it'll be too much trouble. While there isn't a proper test suite yet, can you create a single isolated file (or many files) that covers that various cases? I can also add in a couple that I have in mind. You can add the files inside of `tests/basic`.

**Comment by pparkkin** [comment]
- Added some test files
- Support types and constructors
- Only check top level definitions

**Comment by rahulmutt** [comment]
Looks like you fixed that last build failure, great. Now it's failing on some hackage packages. Will upload the patches and see if I can merge this by tonight. Are there any more pending items from your side?

**Comment by pparkkin** [comment]
I'm not sure if this one is a bug on my side, or something with the library being compiled. I was going to take a look at it tonight.

```
Data/DList.hs:163:1:
    Multiple declarations with names differing only in case.
    Declared at: Data/DList.hs:141:1
                 Data/DList.hs:163:1
```

The code in question uses `pattern`. I'm not sure how I should handle it, and I was going to test to see how it works.

```haskell
pattern Cons x xs <- (toList -> x:xs)
...
cons x xs   = DL ((x:) . unDL xs)
```

If you think it's not a bug with my changes, I'm okay with merging right now.

**Comment by pparkkin** [comment]
Pushed a change for handling pattern synonyms. Hopefully it will take care of the issue in the build.

**Comment by rahulmutt** [comment]
You can run tests locally with `stack test eta` to quickly check whether it worked or not. Travis rebuilds `eta` from scratch so it'll take longer. You've already gotten a built copy with your changes so it'll be faster for you.

**Comment by pparkkin** [comment]
Travis passed. I looked through the AppVeyor log, but couldn't see anything related to my changes.

I think we're good.

**Comment by rahulmutt** [comment]
Great, I think that's a good sign that it's working. Merging.

**Pull request merged**
