### PR TITLE
Fix ArrayIndexOutOfBoundsException with unicode strings

### PR DESCRIPTION
**Pull request by pparkkin**
Fixes https://github.com/typelead/eta/issues/180.

### CODE REVIEW

**Comment by pparkkin** [comment]
I was trying to figure out how to add some tests to `ghc-prim` for things like this, but couldn't figure out how to do that. Seems like without Prelude or much of anything, it's a little tough. Any ideas?

**Comment by rahulmutt** [comment]
Great work! 

You can feel free to use Prelude as well. No need to test *just* ghc-prim since that's hard (you can't print anything in `ghc-prim`!). You can make an Etlas project that has `ghc-prim` and `base` in the `build-depends:` field and try out the following code:
```
{-# LANGUAGE MagicHash #-}

import GHC.CString
import GHC.Types

main :: IO ()
main = print $ unpackCStringUtf8# "SomeUnicodeCharHere"#
```
Just add a comment that it requires both `ghc-prim` and `base`, no need to submit the entire project!
The same bug might afflict some of the other functions that accept UTF8 strings - can you add tests for those as well?

**Comment by pparkkin** [comment]
I couldn't figure out how to call `unpackCStringUtf8#` directly with unicode input. If I try to pass in e.g. `"△"#`, the build fails with a `primitive string literal must contain only characters <= '\xFF'`. I couldn't figure out another way to get a `JString#`.

So I just added a file to print out a bunch of UTF-8 characters.

**Comment by rahulmutt** [comment]
Another way you can get around it:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import GHC.Types
...
let (JS# str) = "SomeUnicodeHere" :: JString
print $ unpackUtf8String# str
```

**Pull request merged**
