### PR TITLE
Update Nix derivations for new test suite

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by puffnfresh** [comment]
@jwiegley this should work!

**Comment by jwiegley** [comment]
`etlas` still fails to build:

```
builder for '/nix/store/cdm8ccbp6fspwjmws4my4hlsrvrb4hzb-etlas-1.4.0.1.drv' failed with exit code 1; last 10 log lines:
  ignoring (possibly broken) abi-depends field for packages
  ignoring (possibly broken) abi-depends field for packages
  unpacking sources
  unpacking source archive /nix/store/zgfpviyzqcx8r8yzg3qz25zxisp5h0m3-etlas
  source root is etlas
  patching sources
  compileBuildDriverPhase
  setupCompileFlags: -package-db=/private/tmp/nix-build-etlas-1.4.0.1.drv-0/setup-package.conf.d -j1 -threaded -hide-package=etlas-cabal
  <command line>: cannot satisfy -hide-package etlas-cabal
      (use -v for more information)
```

**Comment by puffnfresh** [comment]
@jwiegley I have a feeling you have an outdated submodule, maybe.

**Comment by rahulmutt** [comment]
@puffnfresh That may be it. I'll merge this for now. @jwiegley If you still get problems after doing `git submodule update --init --recursive`, feel free to file a new issue.

**Comment by jwiegley** [comment]
Note that I have `git config --global submodule.recurse true` set, so I always update submodules on a pull.  This is what I see:

```
git pull
remote: Counting objects: 700, done.
remote: Compressing objects: 100% (396/396), done.
remote: Total 700 (delta 308), reused 688 (delta 297), pack-reused 0
Receiving objects: 100% (700/700), 89.94 KiB | 1.45 MiB/s, done.
Resolving deltas: 100% (308/308), completed with 44 local objects.
From github.com:puffnfresh/ghcvm
 * branch              nix/fixes  -> FETCH_HEAD
Fetching submodule codec-jvm
Fetching submodule etlas
From https://github.com/typelead/etlas
   b69d186..0ae4612  master                            -> origin/master
 * [new branch]      revert-52-long-path-fix           -> origin/revert-52-long-path-fix
 * [new branch]      revert-53-revert-52-long-path-fix -> origin/revert-53-revert-52-long-path-fix
Fetching submodule etlas/hackage-security
fatal: bad object 0000000000000000000000000000000000000000
```

**Comment by jwiegley** [comment]
Other than that oddness, the build works now!

**Pull request merged**
